### ISSUE TITLE
Please add line under the menu tab

### ISSUE THREAD

**Issue by aleksandrahojszyk** [cyfronet-fid/eosc-search-service#1034]
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=5358%3A13775&mode=design&t=obKcUKcQ3ZPsZncl-1

**Comment by Michal-Kolomanski** [comment]
Done in https://github.com/cyfronet-fid/eosc-search-service/pull/1032
