### ISSUE TITLE
Display services related to specific Interoperability Guidline on IG details page and vice versa

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1035]
Acceptance criteria:
- [ ] As a User I would like to see the services related to specific Interoperability Guidelines on the IG detail page
- [ ] As a User I would like to click on specific services and see the detail page of these service
- [ ] Change the button name from Access Guideline to Read Guideline

Figma:
@aleksandrahojszyk

**Comment by aleksandrahojszyk** [comment]
<3

**Comment by aleksandrahojszyk** [comment]
super
