### ISSUE TITLE
Map providers filter for proper values for Trainings and Interoperability Guidlines collections

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1056]
Acceptance criteria:
- [ ] As a user I would like to see proper mapped values for "Provider/Organisation" filter for Training and IG collections

![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/621e1f08-799f-4249-bbc3-81305c67bdb7)

**Comment by Marcelinna** [comment]
done
