### ISSUE TITLE
Problem with "sort by" on production instance

### ISSUE THREAD

**Issue by eldenkat** [cyfronet-fid/eosc-search-service#1059]
Steps tu reproduce:

1.Go to All Catalogs and try to sort records by most popular
<img width="1301" alt="Screenshot 2023-11-27 at 14 04 41" src="https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/0ea4536e-3c22-4e48-82c2-99a842ee5f57">

2. See results - the label displayed is Date-most recent (instead of most popular)
<img width="1069" alt="Screenshot 2023-11-27 at 14 04 57" src="https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/9ab914d4-9b07-484d-af58-3b8fa8a8156a">

3. Try to change Date-most recent into Most popular:
<img width="1098" alt="Screenshot 2023-11-27 at 14 05 10" src="https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/f6182d23-ac39-4862-a53e-4ab79944f5a8">

4.See- the list of records stays the same, but label has changed into Most popular.

Expected behavior: Fix the bug.

**Comment by Michal-Kolomanski** [comment]
Done
