### ISSUE TITLE
Prepare Solr schema for Marketplace Catalogues

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1123]
Acceptance criteria:
- [ ] As a scope of this issue we should have Solr schema ready to use by developer

This issue is blocked by: https://github.com/cyfronet-fid/marketplace/issues/3068

**Comment by wiktorflorian** [comment]
My proposal to fit the [Figma](https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=60-2227&mode=design&t=UVOKJuahD6s5amJo-0), based on information contained in the [C. v4.00 EOSC Multi-Provider Cat_409f63efbd6a44ffac0406c8c590dff5-181023-1041-6200.pdf](https://github.com/cyfronet-fid/marketplace/files/12999421/C.v4.00.EOSC.Multi-Provider.Cat_409f63efbd6a44ffac0406c8c590dff5-181023-1041-6200.pdf) and [ruby schema](https://github.com/cyfronet-fid/marketplace/blob/6576cd3e2a7b14ac7585426224661d2b45c304eb/db/schema.rb)  here includes the output:

```
catalogue_output_schema = {
    "abbreviation": "string",
    "description": "string",
    "keywords": "array<string>",
    "keywords_tg": "v",
    "title": "string",
    "type": "string",
    "scientific_domain": "array<string>",
    "scientific_subdomain": "array<string>",
    "structure_type": "array<string>",
    "legal_status": "array<string>",
}
```
Which will be converted into this Solr schema:
```
<field name="abbreviation" type="text_general" indexed="true" stored="true" multiValued="false"/>
<field name="description" type="text_general" indexed="true" stored="true" multiValued="false"/>
<field name="keywords" type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name="keywords_tg" type="text_general" indexed="true" stored="true" termPositions="true" termVectors="true" termOffsets="true" required="false"/>
<field name="title" type="text_general" indexed="true" stored="true" multiValued="false"/>
<field name="title_str" type="lowercase" indexed="true" stored="true"/>
<field name="type" type="string" indexed="true" stored="true"/>
<field name=“scientific_domain” type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name=“scientific_subdomain” type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name=“structure_type” type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name=“legal_status” type="strings" indexed="true" useDocValuesAsStored="true"/>
```

Currently, the `legal_status` field is missing, but it will be added in the future. However, there is no obstacle to adding it to Solr at this time. I am also waiting for information about ID.

I also need a decision on which fields, not included in the figma, will be used as filters and added to the schema.

The following fields, which are both in MP, are currently unused:

- pid (I recommend adding this field)
- created_at
- updated_at
- synchronised_at
- website
- legal_entity
- inclusion_criteria
- validation_process
- end_of_life
- street_name_and_number
- postal_code
- city
- region
- country
- participating_countries
- affiliations
- vocabulary (eid, name, description, type, ancestry, ancestry_depth, extras, created_at, updated_at)

According to C. v4.00 EOSC Multi-Provider Catalogue Profile there should also be :

- hosting_legal_entity
- multimedia_url
- multimedia_name
- public_contact_informations (first name, last name, email, phone, position)
- networks

**Comment by wiktorflorian** [comment]
The solr schema, as provided by [Figma](https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=7402-12349&mode=design&t=7xWPpF7Er14YMxuL-0), is as follows:

```
<field name="abbreviation" type="text_general" indexed="true" stored="true" multiValued="false"/>
<field name="description" type="text_general" indexed="true" stored="true" multiValued="false"/>
<field name="id" type="string" termPositions="true" termVectors="true" termOffsets="true" required="true" useDocValuesAsStored="true"/>
<field name="keywords" type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name="keywords_tg" type="text_general" indexed="true" stored="true" termPositions="true" termVectors="true" termOffsets="true" required="false"/>
<field name="title" type="text_general" indexed="true" stored="true" multiValued="false"/>
<field name="title_str" type="lowercase" indexed="true" stored="true"/>
<field name="type" type="string" indexed="true" stored="true"/>
<field name=“scientific_domain” type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name=“structure_type” type="strings" indexed="true" useDocValuesAsStored="true"/>
<field name=“legal_status” type="strings" indexed="true" useDocValuesAsStored="true"/>
```

The output is as follows:

```
catalogue_output_schema = {
    "abbreviation": "string",
    "description": "string",
    "id": "string",
    "keywords": "array<string>",
    "keywords_tg": "v",
    "title": "string",
    "type": "string",
    "scientific_domain": "array<string>",
    "structure_type": "array<string>",
    "legal_status": "array<string>",
}
```
