### ISSUE TITLE
DOI, Handle in Advanced Search

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1180]
- [ ] We need to ask Wiktor how many HANDLE are in use
- [ ] Consultation with Ania

**Comment by AlicjaSwierad** [comment]
figma: https://www.figma.com/file/VEJHiowgFv2sKfCTaPrUGf/EOSC---Ala?type=design&node-id=2117%3A37396&mode=design&t=Lz2cZpFGIC2imIhM-1
