### ISSUE TITLE
Automate the download of statistics from GA

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1203]
Acceptance critiera:
- [x] Download statistics from this page:
https://docs.cyfronet.pl/pages/viewpage.action?pageId=139657523
- [x] Try to download statistics per page (for detaild page in MP and SS)

**Comment by wiktorflorian** [comment]
Regarding point 1.

The Marketplace data is from July 2022, while the Search Service data is from January 2023 and the EOSC Portal data is from May 2023.

 All specified statistics from [confluence](https://docs.cyfronet.pl/pages/viewpage.action?pageId=139657523) can be downloaded, including additional data. However, the average engagement time (in minutes) is calculated only for first-time users, not all active users.

For specific values, please refer to the following:

- Number of users -> Metric: `activeUsers`.
- Number of new users -> Metric: `newUsers`.
- Number of returning users -> `returning` part of Dimension: `newVsReturning`.
- Number of sessions -> Metric: `sessions`.
- Average engagement time (in minutes) -> Metric: `userEngagementDuration` / Dimension: `engagedSessions` / 60.
- Number of engaged sessions -> Dimension: `engagedSessions`.
- Channels for traffic -> Dimension: `sessionDefaultChannelGroup`.
- Country -> Dimension: `country`.
- Device category -> Dimension: `deviceCategory`.
- Even count -> Dimension: eventName Metrics: `eventCount`.

For more metrics and dimensions, refer to [API Dimensions & Metrics](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema).

To automate the download of these metrics and dimensions, a simple script can be created.

**Comment by wiktorflorian** [comment]
Active users, sessions, and other metrics can be used to determine the usage of Search Service and Marketplace specific paths or search queries. However, we should narrow down the paths we want to track, as there were 1,099 different page paths in January 2024.

**Comment by wiktorflorian** [comment]
This is the current result:

- [ga4_marketplace_data.xlsx](https://github.com/cyfronet-fid/eosc-search-service/files/14445214/ga4_marketplace_data.xlsx)
- [ga4_search service_data.xlsx](https://github.com/cyfronet-fid/eosc-search-service/files/14445216/ga4_search.service_data.xlsx)
- [ga4_portal_data.xlsx](https://github.com/cyfronet-fid/eosc-search-service/files/14445215/ga4_portal_data.xlsx)

TO DO:
- [ ] Analysis for SearchTerm.
- [ ] Choosing top pages.
- [ ] Deep dive into search queries left.
