### ISSUE TITLE
Map scientific domains for Training Catalogue

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1212]
Acceptance criteria:
- [ ] As a User I would like to see the scientific domain for Training Catalogue display in proper manner (without _)

Raw input:
<img width="313" alt="image" src="https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/379e8e58-bbf3-4e55-8df9-8157820e2df7">

Scope for now:
- hardcode the mapping as a whole 
- satisfy the needs of current rules:
remember about the rules: https://github.com/cyfronet-fid/eosc-search-service/blob/4ac32f1e613aa1a397230b2ffe6f1aeff2000a66/transform/app/transform/utils/common.py#L175. 
Resources are bound to scientific subdomains but we need also to add parent for every child.

Example:
So e.g. when some resource has a scientific subdomain:
RAW:
`scientific_subdomain-engineering_and_technology-other_engineering_and_technology_sciences`

Expected output from that one scientific subdomain:
`"Engineering & Technology>Other Engineering & Technology Sciences", "Engineering & Technology"`

Scope when PC will repair the bug:
- from a standard get trainings query (https://providers.eosc-portal.eu/api/public/trainingResource/all?catalogue_id=all&active=true&suspended=false&quantity=10000 or beta) get scientific subdomains. PC does not return root scientific domains in public API - reported to them as a bug.
- hardcode root scientific domain mapping
- map scientific domains to the already established form: https://github.com/cyfronet-fid/eosc-search-service/blob/2a44f008ba226b687777f9c32f0559486eed530e/transform/app/transform/mappings/scientific_doamin.py#L5

**Comment by Michal-Kolomanski** [comment]
- [ ] check if that is used anywhere, if not delete https://github.com/cyfronet-fid/eosc-search-service/blob/development/ui/apps/ui/src/app/dictionary/trainingDomainDictionary.ts

**Comment by wiktorflorian** [comment]
it is referenced here https://github.com/cyfronet-fid/eosc-search-service/blob/development/ui/apps/ui/src/app/dictionary/runDictionaryForInteroperabilityGuidelines.ts, however function where it is located is not used.
