### ISSUE TITLE
Map Resource Type for Training Catalogue

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1213]
Acceptance criteria:
- [ ] As a User I would like to see all fields for Resource Type filter mapped to the proper value (map from: tr_dcmi_type-unit_plan to: Unit Plan )

See:
<img width="282" alt="image" src="https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/010c136f-e6f0-4824-bcdf-788524963ce3">

**Comment by Michal-Kolomanski** [comment]
Add new value here: https://github.com/cyfronet-fid/eosc-search-service/blob/67d27158b7efc350875b81103b821a30c140bd90/transform/app/transform/transformers/training.py#L236
