### ISSUE TITLE
Update documentation license in sharepoint & repository

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1226]
Edit existing license.txt (in all our services):
- currently, there is only GPL3 content.

Update in a way:
Software license:
GPL3 content

Software documentation license:
CC-BY content

**Comment by wiktorflorian** [comment]
This is the final version of the license.txt.
[LICENSE.txt](https://github.com/cyfronet-fid/eosc-search-service/files/14444639/LICENSE.txt)

**Comment by wiktorflorian** [comment]
At Sharepoint, it was replaced in three locations.

- EOSC Marketplace and Search Service (Cyfronet)
- EOSC User Dashboard (Cyfronet)
- Order Management System in the EOSC Catalogue (Cyfronet)

PR in [Software-Documentation](https://github.com/EOSC-PLATFORM/Software-Documentation/pulls) was created to replace `licence.txt` in:
- EOSC Marketplace and Search Service (Cyfronet)
