### ISSUE TITLE
Update  AS Guide (screenshots)

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1240]
- [x] It should be changed after adding the button for Advanced Search

**Comment by eldenkat** [comment]
@maria-j-k 
https://docs.google.com/document/d/1FCi0Bd3_LGMq6-fth8C7ir-xqkAfD-RuLjB53JQ-z84/edit?usp=sharing

![Image](https://github.com/user-attachments/assets/9f902b1c-d743-4d91-8e5b-330972cfb5c7)
![Image](https://github.com/user-attachments/assets/009cef72-578a-41d5-8373-99476247ca9f)
![Image](https://github.com/user-attachments/assets/41455e6d-8544-4cc5-9de3-638b314e250b)
![Image](https://github.com/user-attachments/assets/47c27a75-c618-4167-9507-78dab19aab11)
![Image](https://github.com/user-attachments/assets/764186dd-53f0-4fd5-b6ff-44e4f8a29a02)
![Image](https://github.com/user-attachments/assets/1ee8fd80-5939-475c-99ae-c23c0428f292)
![Image](https://github.com/user-attachments/assets/da31b8ad-72ed-4173-9077-0d3645c700aa)
![Image](https://github.com/user-attachments/assets/adffc985-6c4d-4d30-965c-b90afdae9a38)
