### ISSUE TITLE
DOI box should redirect to source

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#1246]
1. Type some data in DOI in Advance Search
2. Click on Doi blue box
3. Doi is as filter
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/2cee5061-075f-4824-a53f-3bed22f2191d)

.............................................................................
1. Type some data in title in Advance Search
2. Click on DOI blue box
3. See user is redirected to the outer side
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/cd15a078-c5fc-49cc-9f55-c8f1c4de93f2)
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/aacd8210-4e92-4777-9ebe-ea49a211e34c)

**Comment by eldenkat** [comment]
https://docs.google.com/document/d/1FCi0Bd3_LGMq6-fth8C7ir-xqkAfD-RuLjB53JQ-z84/edit
AS Guide - red text is new
