### ISSUE TITLE
Make slides with screenshots of new functionalities

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1296]
We need screenshots for:
- new design of the service page for Services and Datasources
- suspended status
- Catalogs landing page nad catalogs in Search Service
- bundles for users and from backoffice perspective
- new design of service offers form (back office ) nad predefined schema
- Pinning Research Products to the Marketplace Projects

**Comment by AlicjaSwierad** [comment]
Screenshots:
https://www.figma.com/file/687A8OZrlBnyhpvIgbKVBy/Screens?type=design&node-id=21%3A31&mode=design&t=fqr9GjZYfWG191n0-1
