### ISSUE TITLE
Research on Current Solutions and Trends in the Research Ecosystems

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1316]
We need to understand the current landscape and future trends in the EOSC & different catalogues ecosystems to guide our strategic planning. The focus will be on:

**Current Solutions:**
- [ ] Identify key players and their offerings - what is already offered in the scope of EOSC projects and numerous more local catalogues like catalogues from our current use cases etc
- [ ] Analyze their strengths and weaknesses.
- [ ] Analyze user feedback and satisfaction levels from previous projects*

**Future Trends:**
- [ ] Forecast shifts in user needs and preferences.
- [ ] Investigate emerging technologies and methodologies*
- [ ] Explore upcoming regulatory changes and funding opportunities*

Notes:
Please do not hesitate to contact as much as you want @roksanaer @Michal-Kolomanski @agpul

**Comment by aleksandrahojszyk** [comment]
założenie: patrzymy i analizujemy strony portale software itp z perspektywy takiej, żeby zobaczyć nie tylko warstwę interfejsu i funkcjonalności, ale potrzeby użytkowników które one spełniają

**Comment by aleksandrahojszyk** [comment]
https://docs.google.com/document/d/1q8pIXM0xRm8I71cwX5bD3Kpng-ie8_oeCSguYZVyqzA/edit
