### ISSUE TITLE
Design DOM 

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1334]
We should rename it to something more meaningful and sellable.

**Comment by Michal-Kolomanski** [comment]
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/d58fa368-62a7-405d-8499-6a6aed2ea449">

**Comment by AlicjaSwierad** [comment]
UI proposal for become a provider plus a slogan:
https://www.figma.com/design/cWMFTs2ELpDjgchcUzAMCx/Landing-Page---Whitelabel?node-id=9111-9085&t=e9ngHFZIc6l8mu6x-1
