### ISSUE TITLE
Deploy/expose postgres instance for beta (sandbox) search service

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1363]
Scope: 
- [ ] Decide whether it is better to deploy a dedicated Postgres instance to store all data types for the sandbox search service. Or should we just expose and increase the storage capacity of the already existing Postgres instance?
- [ ] How much storage do we have reserved for beta solr? It should be similar, just a little bit more. Remember it's beta. In the future, we will need a Postgres instance for prod also. It should store at least 2 full data iterations. 1 iteration is around 25GB. On beta Postgres instance, there will be no need for replication. 
- [ ] Expose this Postgres instance to beta transformer (they should see each other)
- [ ] Expose Postgres to users with Cyfrone's VPN to make querying possible. 

I assume that our Postgres does not have any web interface?

**Comment by roksanaer** [comment]
lets assume we need 100 GB of storage
