### ISSUE TITLE
Add buttons for changing data scope context

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1382]
- make a branch from `new-eosc-pl `
- see the design preview below in the comment (try to make those button in the same place/similar style)
- data is taken from sol beta instance http://149.156.182.2:8983/solr/#/~collections. See e.g. pl_dataset alias

Scope: 
- [x] Create PL and EU buttons. Those buttons should be placed somewhere at the top. Because they are the most paramount
- [x] (Frontend-wise) those buttons should define which data collections are presented in:
<img width="733" alt="image" src="https://github.com/user-attachments/assets/6359fa35-376f-427f-84d0-513cef97aaab">
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/4b1a0a65-a4c6-46a9-8444-7a0df55f499c">

- [x] (Backend-wise) those buttons should set (on client side):
- PL: `COLLECTIONS_PREFIX='pl_'`
- EU: `COLLECTIONS_PREFIX=''`

- [x] Data scopes for buttons:
- PL: All Resources, Publications, Data, Services
- EU: No change

- [x] Hide providers and catalogues for PL & EU

**Comment by AlicjaSwierad** [comment]
UI preview as a reference @maria-j-k 
![image](https://github.com/user-attachments/assets/b3f3b85a-0119-4b5e-9dab-9071ba47d00f)
