### ISSUE TITLE
Style: Apply Design Styles to the PL-EOSC Instance of the Search Service

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1392]
Style the interface according to the provided design specifications.

**Navigation bar - categories**

- icons in the comment
- 3 states needed - default, hover and focus
- 
1. https://www.figma.com/design/xTTrqo17a8ORVXYQFLXeeD/%F0%9F%87%B5%F0%9F%87%B1-Search---Polski-EOSC?node-id=9080-2276&node-type=section&t=tcqXWwdGC87GfuBY-0

**Search bar**

- Tabs for providers and categories were moved to the right panel
- Colors were tweaked to match accessibility standards
- Add a tooltip

2. https://www.figma.com/design/xTTrqo17a8ORVXYQFLXeeD/%F0%9F%87%B5%F0%9F%87%B1-Search---Polski-EOSC?node-id=9070-2237&node-type=section&t=Fu8ulv4ehsEEzG4R-0

**Right panel**
3. https://www.figma.com/design/xTTrqo17a8ORVXYQFLXeeD/%F0%9F%87%B5%F0%9F%87%B1-Search---Polski-EOSC?node-id=9095-2673&t=nTXUWhZTLHgNTAa4-1

**Comment by AlicjaSwierad** [comment]
Background image + background logo ⤵️

![Image](https://github.com/user-attachments/assets/2caecbf2-61fd-40d3-a65d-52cb358fbf71)

![Image](https://github.com/user-attachments/assets/1f57842d-62b8-4197-b30f-859de24f5199)

**Comment by AlicjaSwierad** [comment]
Right panel card's background img ⤵️
![Image](https://github.com/user-attachments/assets/edf91c5e-69b3-49fc-b91d-8bdab99054df)
