### ISSUE TITLE
Move Landing Page of the eosc-pl whitelabel from MP to SS

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#1422]
- [ ] Transfer the landing page to SS (RDS).
- [x] Update the content per the latest agreements (e.g., carousel of anonymous partners, etc.) according to Figma Design @AlicjaSwierad

**Comment by AlicjaSwierad** [comment]
Figma:
https://www.figma.com/design/Roz3vPZuvOyHx2RlDeakDW/%F0%9F%87%B5%F0%9F%87%B1-Landing-Page---Polski-EOSC?node-id=9259-3703&t=JJ1jMekbpzTFerED-1
