### ISSUE TITLE
Improve show more functionality

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#143]
We need to a "show more" functionality, according to Marcelina's tests still some problems with this functionality occurs.
1. After picking the filter show more disappears.
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/1182ff99-a0cb-411a-a4f0-b6658b25501e)

2. "Show more" should exist on all of the buttons, now we have show more only for a few of them:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/868ba1e6-0b88-4f79-94ac-393dc63775d7)

![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/5074f476-43a1-44b9-9725-cc43e304ddea)

**Comment by danielkryska** [comment]
An old issue to the previous iterations.
