### ISSUE TITLE
Cleaning data

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-search-service#164]
Pre-requisites
- [ ] what do we expect from data?

TODO
- [ ] remove special chars or records containing it

**Comment by danielkryska** [comment]
Not allowed signs:
- HTML like https://www.toptal.com/designers/htmlarrows/symbols/
- \, /, (, ), [, , ], ', ", |, ...

Allowed
- >, &, ',',

**Comment by danielkryska** [comment]
The issue may be solved by providing better serializers on the UI side.

**Comment by Marcelinna** [comment]
Author name can be 
    'name, surname
    'name surname'
    'surname'
    'name first letter second name. surname' --> Paul E. Wagner

**Comment by Marcelinna** [comment]
![image](https://user-images.githubusercontent.com/59872096/188086067-8cec6d53-702e-4ea4-b2d2-a9bfd880652b.png)
which characters are displayed like this?
