### ISSUE TITLE
Add the ability to search Trainings in the main search bar

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#170]
![image](https://user-images.githubusercontent.com/59872096/187896861-8c3fbd8b-3a64-4395-a233-f9efc60983ab.png)
![image](https://user-images.githubusercontent.com/59872096/187896694-d0429798-2118-4c52-a960-e4763dfc0795.png)

**Comment by agpul** [comment]
It works
