### ISSUE TITLE
  Filter consistency with OpenAire

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#219]
1. Change name

 **Scientific Domain** filter should be changed to **Scientific Domain [Beta]**

2. Add missing filter

 For **Data** collection
Field of Science [Beta]

 For **Software** collection
Field of Science [Beta]
SDG [Beta]

**Comment by Michal-Kolomanski** [comment]
> 1. Change name
> 
> **Scientific Domain** filter should be changed to **Scientific Domain [Beta]**
> 
> 2. Add missing filter
> 
> For **Data** collection Field of Science [Beta]
> 
> For **Software** collection Field of Science [Beta] SDG [Beta]

Regarding the second part about data:
- publications have sdg and fos,
- datasets have only sdg,
- software does NOT have any of those.

**Comment by agpul** [comment]
After consultation I've decided to close this issue for now.
