### ISSUE TITLE
UI per product type - problems

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#220]
**Publications**
![image](https://user-images.githubusercontent.com/59872096/193244261-bc3e0c3c-e2c5-445c-b07c-bf26f195564f.png)
![image](https://user-images.githubusercontent.com/59872096/193244304-57ada390-f170-48b8-82ac-09d27a800e3c.png)
1. Lack of Licences
2. Lack of Scientific domain    (Field of Science)

**Data**
![image](https://user-images.githubusercontent.com/59872096/193244761-31e0ba09-8262-4527-a113-59fc2f7065ca.png)
![image](https://user-images.githubusercontent.com/59872096/193244790-2684e317-194c-4a5a-bf4f-e856c796ba92.png)
1. Lack of Licences
2. Publication date should not be visible
3.  Lack of Scientific domain    (Field of Science)
4. Change Dataset to Data

**Software**
![image](https://user-images.githubusercontent.com/59872096/193245516-f6d1b56a-bb99-44f0-a4f9-a19b19d65890.png)
![image](https://user-images.githubusercontent.com/59872096/193245326-ab3e8d2b-6f2b-459a-b3fd-c1882a83c54d.png)
1. Lack of Licences
2. Publication date should not be visible
3. Publisher should not be visible
5. Document type should not be visible
6.  Lack of Scientific domain    (Field of Science)

**Training**
![image](https://user-images.githubusercontent.com/59872096/193245914-dd6ff482-7437-4c50-a6b9-a42cfdfe2abc.png)
![image](https://user-images.githubusercontent.com/59872096/193245976-f647e51c-b496-4899-ad52-6091702a0984.png)
1. Lack of Create on date
2. Make access right before licence

**All catalog**
The products in All catalog should look exactly the same like in the products page!

**Comment by danielkryska** [comment]
Publications
1. Lack of license -> **missing data for it, ask @Michal-Kolomanski**
2. FoS -> **done** !!!IMPORTANT!!! Not all resources contain this field!!!

Data
1. Lack of Licences -> **missing data for it, ask @Michal-Kolomanski**
2. Publication date should not be visible -> **done**
3. Lack of Scientific domain (Field of Science) -> **done** !!!IMPORTANT!!! Not all resources contain this field!!!
4. Change Dataset to Data -> *data migration required, ask @Michal-Kolomanski**

Software
1. Lack of Licences -> **missing data for it, ask @Michal-Kolomanski**
2. The publication date should not be visible -> **done**
3. The publisher should not be visible -> **done**
4. Document type should not be visible -> **done**
5. Lack of Scientific domain (Field of Science) -> **done** !!!IMPORTANT!!! Not all resources contain this field!!!

Training
1. Lack of Create on date -> **needed migration in data, ask @Michal-Kolomanski**
2. Make access right before license -> **done**

**Comment by Michal-Kolomanski** [comment]
> Publications
> 
> 1. Lack of license -> **missing data for it, ask @Michal-Kolomanski**
> 2. FoS -> **done** !!!IMPORTANT!!! Not all resources contain this field!!!
> 
> Data
> 
> 1. Lack of Licences -> **missing data for it, ask @Michal-Kolomanski**
> 2. Publication date should not be visible -> **done**
> 3. Lack of Scientific domain (Field of Science) -> **done** !!!IMPORTANT!!! Not all resources contain this field!!!
> 4. Change Dataset to Data -> _data migration required, ask @Michal-Kolomanski_*
> 
> Software
> 
> 1. Lack of Licences -> **missing data for it, ask @Michal-Kolomanski**
> 2. The publication date should not be visible -> **done**
> 3. The publisher should not be visible -> **done**
> 4. Document type should not be visible -> **done**
> 5. Lack of Scientific domain (Field of Science) -> **done** !!!IMPORTANT!!! Not all resources contain this field!!!
> 
> Training
> 
> 1. Lack of Create on date -> **needed migration in data, ask @Michal-Kolomanski**
> 2. Make access right before license -> **done**

1) FOS and SDG will be available for `publications` and also `datasets`, `software`, see  [stats](https://docs.google.com/spreadsheets/d/1kbh1ndrM2eePksVhlxZV3XTD3fHYCzN72kpAgmbVc40/edit#gid=0) provided by Miriam.

2) Lack of license - yes there is no license for OAG resources. The schema was prepared and accepted [Search Service requirements](https://docs.google.com/document/d/1bav69NTLSS8WFmhO18JbKi568ltOOhA4tUKdS7_i9_g/edit#heading=h.pu1x9dmzqspj) 
So if we want to have a field license:
2.1) I have to locate that information in the dump and confirm that this is the right field (can be many licenses in different fields) 
2.2) process that, 
2.3) update solr schema
2.4) post new data. 
It is doable but how much priority should be on that? @agpul 

3)` Lack of Create on date -> needed migration in data` - for trainings what does it mean? Do we miss the `publication_date` for trainings?

**Comment by agpul** [comment]
@Michal-Kolomanski License has less priority than Datasets

**Comment by agpul** [comment]
I close this ticket as it is not relevant (we are going to have new box view)
