### ISSUE TITLE
Lack of Scientific domain, Organisation for Services in All Catalogs

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#235]
All Catalogs
![image](https://user-images.githubusercontent.com/59872096/194008867-d16ef1f8-20fa-46a7-9b38-6a657cd52ed8.png)

Services
![image](https://user-images.githubusercontent.com/59872096/194008819-3c0c7d60-81cc-4b51-b4ac-188cf8febbce.png)

**Comment by agpul** [comment]
Change the filed that is assigned to DOI according to updated schema.
