### ISSUE TITLE
Change names for Related Platforms (Services and Datasources) 

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#238]
names should be as in MP
 SS
![image](https://user-images.githubusercontent.com/59872096/194010099-2fb8686e-5926-4769-9079-454863ac6ec5.png)

MP
![image](https://user-images.githubusercontent.com/59872096/194010310-20a65d55-15df-48ea-bd5e-1088b88d687d.png)

**Comment by Michal-Kolomanski** [comment]
I see 3 solutions:
1) Get better data from MP - data should be as it is in MP. With @goreck888 support. Perforable.
2) Map 1 record to 1 - e.g. `related_platform-egiace` -> `EGI-ACE `. Hard to maintain, and painful.
3) Remove `related_platform-` part from records and capitalize the rest. Disadvantage: `related_platform-egiace` will be mapped into `EGIACE`, not `EGI-ACE` as it should be. So it also will require some maintenance and time. 

So 1) solution seems to be the answer - so in my code, there will be no change, only data delivered to me have to change

**Comment by agpul** [comment]
@goreck888 - we choose solution number 1

**Comment by goreck888** [comment]
Just use `platforms` instead of `related_platforms` field in data I've provided :smiley:
