### ISSUE TITLE
Tags duplicate filter values on click

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-search-service#266]
![image](https://user-images.githubusercontent.com/31220811/196619671-8734ed24-ca98-49d2-aff9-c1a81a28ee25.png)

Step to reproduce

1. Go to [Trainings]
2. Click on License for one of the trainings result
3. Click second time to License 
4. See problem - Filter is duplicated
![image](https://user-images.githubusercontent.com/59872096/198557389-a26cbc9e-a9e9-42e3-b49a-4b154a6e0fb1.png)

The same case for language in Services
![image](https://user-images.githubusercontent.com/59872096/198558699-f96b2c57-8841-42db-8076-cd94f4a7ff1d.png)

**Comment by Marcelinna** [comment]
Step to reproduce

1. Go to [Trainings]
2. Click on License for one of the trainings result
3. Click second time to License 
4. See problem - Filter is duplicated
![image](https://user-images.githubusercontent.com/59872096/198557389-a26cbc9e-a9e9-42e3-b49a-4b154a6e0fb1.png)
