### ISSUE TITLE
Connect the Search Service with GA4

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#268]
As a scope of this issue, we need to have the search service connected to Google Analitycs to reach the basic metrics.

**Comment by biometricsmw** [comment]
Google Analytics - introduction to GA4 (https://support.google.com/analytics/answer/10089681), how to introduce GA4 in Python (https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py)

As Universal Analytics (UA) is deprecated, should we place GA4 in the project? The information we can collect are as follows - https://support.google.com/analytics/answer/9964640?hl=en#zippy=%2Cin-this-article 

Thanks in advance for your response @agpul  :)

**Comment by agpul** [comment]
yes, we should replace it:)
