### ISSUE TITLE
Restore Anca's categorization

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#292]
Acceptance criteria:

- [x] As a user I can see the filter with the first level of Anca's categories in All catalogs named "Research step"
- [x] As a user I can click on Discover Research Outputs and see all Data+Software+Publications chosen (in All catalog tab)
- [x]  As a user I can click on Access training material and I have all Training chosen (in All catalog tab)
- [ ] As I user I can see Access computing and storage resources instead of Access Computing Resources
- [ ] As a User I can see additional category called "Manage research data" under browse and in the box (currently empty)
- [ ] As a User I can see descriptions of the categories listed, according to the spec provided:
![image](https://user-images.githubusercontent.com/38095945/200541151-83863410-e6ae-4668-86f9-33292181315e.png)
(please notice that in this picture there is an old name for 'Access computing and storage resources' category)

**Comment by danielkryska** [comment]
new field: `unified_categories`
values type: array<string>
values format: 'lvl 1>lvl 2>lvl 3'

Logic:
1. `Discover research outputs`, if `type` is `dataset` or `publication` or `software`
2. `Training material`, if `type` is `training`

**Comment by agpul** [comment]
I am closing this ticket as we will consider a tree for this categorisation and this one may not be relevant.
