### ISSUE TITLE
Multiple words search improvement

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-search-service#319]
**Possible cause**
SOLR queries have set up by default the wrong operator `OR` instead of `AND`.

**How to improve it?**
Add to each request `&q.op=AND`.

**Sources**
![image](https://user-images.githubusercontent.com/31220811/201025127-b265d77a-3980-4e45-8587-28262c96c84a.png)
https://stackoverflow.com/questions/24642900/solr-difficulty-getting-fuzzy-search-with-multiple-terms

![image](https://user-images.githubusercontent.com/31220811/201025182-fc9e2138-e3e5-40e1-bb43-8c033ff77236.png)
https://stackoverflow.com/questions/14226424/changing-the-default-operator-from-or-to-and-in-solr-magento-enterprise

**Comment by Marcelinna** [comment]
duplicate https://github.com/cyfronet-fid/eosc-search-service/issues/404?
