### ISSUE TITLE
Deploy Search Service

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/eosc-search-service#32]

**Comment by wziajka** [comment]
Done
UI   - https://eosc-search-service.grid.cyfronet.pl/
API - https://api.eosc-search-service.grid.cyfronet.pl/

**Comment by jswk** [comment]
Why is the traffic from UI directly hitting the API though?
![image](https://user-images.githubusercontent.com/583197/155986037-6daa1a3b-b9c7-4d86-87a4-4994e74c0eae.png)
The `/api/web` prefix were to be reverse-proxied by UI server to API.
