### ISSUE TITLE
Improve text formating in SS

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#361]
# !!! IMPORTANT !!!
Currently, with highlight feature #367 we are rendering text with HTML tags, due to security reasons we needed to strip HTML from the description. 

When we will work on the issue on the data transformation site we need to remove it in UI!!!!

---

In OpenAire the products description look nice. In Search Service, we have a problem with text formatting.
See:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/b75587e1-42e3-461c-847f-6dc0d33e5b0c)

**Comment by danielkryska** [comment]
First output in google search:

```
Dynamically rendering arbitrary HTML on your website can be very dangerous because it can easily lead to XSS attacks. Only use v-html on trusted content and never on user-provided content.
```

**Comment by agpul** [comment]
After planning: "dwa pola jedno do wyszukiwania a drugie do wyświetlania - MichałSz."
