### ISSUE TITLE
Search by long title problem

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#404]
Service title:
SeaDataNet European Directory of the Initial OceanObserving Systems

Develop
![image](https://user-images.githubusercontent.com/59872096/209125676-fba253ea-38fe-4fe4-8e7e-e23d1eca27c1.png)

Production
![image](https://user-images.githubusercontent.com/59872096/209125647-c495d544-34ad-41af-9efa-4d9429af0f07.png)

**Comment by tomaszandel** [comment]
In develop it looks fixed:
<img width="942" alt="Zrzut ekranu 2023-02-5 o 17 16 56" src="https://user-images.githubusercontent.com/11340871/216821235-f27ef51a-94d4-4125-a539-672c3511aea5.png">
