### ISSUE TITLE
No highlighting for the Trainings collection

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#460]
Publications
![image](https://user-images.githubusercontent.com/59872096/222660288-bd58ffb2-a2b9-4c77-86f4-48917950a714.png)

Trainings
![image](https://user-images.githubusercontent.com/59872096/222660338-ece8a4b9-ec08-4347-9e72-0ed490216beb.png)

**Comment by agpul** [comment]
Duplication [#824](https://github.com/cyfronet-fid/eosc-search-service/issues/824)
