### ISSUE TITLE
Delete landing page from SS

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-search-service#479]
https://search.marketplace.eosc-portal.eu/error/404
1. Go to https://search.marketplace.eosc-portal.eu/error/404
2. Click "Take me to home page"
3. User is on https://search.marketplace.eosc-portal.eu/
![image](https://user-images.githubusercontent.com/59872096/224956227-f75fad5a-becb-43b3-844b-9ecf12bba9a2.png)

button "Take me to home page" should redirect to https://search.marketplace.eosc-portal.eu/

**Comment by agpul** [comment]
Estimation: 1 day
