### ISSUE TITLE
Connect UI to API

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/eosc-search-service#48]
Connect search bar and other filters + results to the actual search service API.

**Comment by danielkryska** [comment]
- search and show results on site
- pagination
- implement cursor to paginate

**Comment by danielkryska** [comment]
https://solr.apache.org/guide/8_11/the-standard-query-parser.html
https://solr.apache.org/guide/8_11/json-facet-api.html
https://solr.apache.org/guide/8_11/faceting.html
https://solr.apache.org/guide/8_11/transforming-result-documents.html
https://solr.apache.org/guide/8_11/pagination-of-results.html
