### ISSUE TITLE
Redesign "Providers" in SS 🔥

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#515]
Like IG

https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=3049%3A17709&mode=design&t=CAe5MLx9x0wHO8VV-1

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=3049%3A17709&mode=design&t=CAe5MLx9x0wHO8VV-1
