### ISSUE TITLE
Adjust the KH landing page, and remove parts without input

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#595]
Please find here the links that are missing to finalize the KH page.
1st block of boxes:
Training resources - LINK = https://search.marketplace.eosc-portal.eu/search/training?q=*
Courses - LINK = https://openplato.eu/blocks/catalog/list.php?searchurl=1&categories=127
Learning paths - LINK = https://openplato.eu/blocks/catalog/list.php?searchurl=1&categories=163
The 2nd block please add the following link for all learning paths
LINK = https://openplato.eu/blocks/catalog/list.php?searchurl=1&categories=163

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/LBrGegZUrQw8uhgIPrx6mh/Knowledge-Hub?type=design&node-id=433%3A8570&t=hIPP1cd8t19NAsvi-1
