### ISSUE TITLE
Change the order of displaying data in "Product types" filter

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#600]
Acceptance criteria:
- [ ]  As a User I want to see the data in "Product types" filter sorted by values based on the number of elements in it (from the highest number )

**Comment by wujuu** [comment]
@agpul @Marcelinna is this still relevant? 

There is no "Product types" filter and besides, every filter is already sorted by the number of elements by default

**Comment by agpul** [comment]
can be closed
