### ISSUE TITLE
 loading s3 dumps into Solr

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/eosc-search-service#61]
* [ ] ~~test for 20 files on non-ssd harddrive~~
* [x] test for 50% publications
* [ ] check multiple threads for post to solr or solr processing (two sets of 20files, two scripts, observe)

**Comment by jswk** [comment]
See [loader](https://github.com/cyfronet-fid/eosc-search-service/tree/main/loader) module for scripts and description of how to run them.

**Comment by kmarszalek** [comment]
for one shard collection solr getting too slow for our usecase.
next step will be:
- check responsive of Solr and determine breaking point, then make multi-shared Solr
