### ISSUE TITLE
All catalogs - "find bundle' filter - only 1 bundle is visible

### ISSUE THREAD

**Issue by eldenkat** [cyfronet-fid/eosc-search-service#675]
1. Go to 'all catalogs'
2.  See 'Research step' filter, 'find bundle'
![2023-06-16 (4)](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/a270d828-eb50-47b1-aeda-e2c13f97d22b)

3. There is only one bundle, instead of 8 available
4. 
**Expected behavior**
Fix the bug

**Comment by Marcelinna** [comment]
now works
