### ISSUE TITLE
Fix the Name Type field in the IG and the frame

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#681]
See problem:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/dae0e3d3-83d6-46c9-9cc0-7db4d474afb5)

https://search.marketplace.eosc-portal.eu/guidelines/eosc.174f9db9e6f21a9868c6d5f25df892c0?return_path=search%2Fguideline&search_params=q%3D*

**Comment by Anok666** [comment]
Done
