### ISSUE TITLE
Single API endpoint for filters

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/eosc-search-service#718]
Currently to display filters every filter makes a separate request to backend search API in order to retrieve facetes, and possible field values. This is suboptimal as it creates a lot of requests which slows down a browser.
The scope of this issue is to create a separate endpoint in `/api/web/search-filters` which should return a map of all filters (which should be a modified concatenation of the responses from the separate filters requested now.

Currently responses have format:

```
{
    "numFound": 4648283,
    "nextCursorMark": "*",
    "results": [],
    "facets": {
        "count": 4648283,
        "unified_categories": {
            "buckets": [
                {
                    "val": "Discover Research Outputs",
                    "count": 4647889
                },
                ...
```

The response format of the new endpoint should be:

```
{
"<filter name (eg. unified_categories)>": [
                {
                    "val": "Discover Research Outputs",
                    "count": 4647889
                },
                ...
]
}
```

All requested filters should be in the response.

The new endpoint should take all basic parameters as search endpoint and perform all solr queries (preferably concurently).
The response should be cached for the given set of input params. Caching time should be configurable via env variable (and be defined in config). The default should be 5 minutes.

**Acceptance criteria:**

No regressions regarding working of filters
When inspecting network requests number of requests should be reduced to only one`/api/web/search-result` and one`/api/web/search-filters`

**Comment by agpul** [comment]
Estimation: 1day
