### ISSUE TITLE
Improve "Country" filter

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#733]
Acceptance criteria:
- [ ]  As a User I want to see the full name of the country in the filter view for eg. Poland for PL
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/1e24d210-69fd-4afe-b40b-5319594d793f)

**Comment by Marcelinna** [comment]
done 
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/8cc16f26-0eb8-4647-9bd6-6315d8009295)
