### ISSUE TITLE
Fix the Scientific Domain view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#737]
- [ ] As a User I want to see only the first leaf of the Scientific Domain in the box view according to the Figma design: @aleksandrahojszyk 

References:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/0d005925-356a-4997-a01d-9bb17efcec00)

**Comment by agpul** [comment]
Estimation: 1 day

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=3964%3A25660&mode=design&t=7KdS0tobZut4oulh-1

**Comment by aleksandrahojszyk** [comment]
![Uploading Screenshot 2023-07-24 at 16.15.30.png…]()

**Comment by aleksandrahojszyk** [comment]
<img width="607" alt="Screenshot 2023-07-28 at 16 10 35" src="https://github.com/cyfronet-fid/eosc-search-service/assets/49695272/4dfe81c5-44ca-4d53-9a84-e53fd1872de9"> 

https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=3964%3A25660&mode=design&t=dblacMS21P41yd3n-1
