### ISSUE TITLE
Fix the data in the Search Service for different types of products

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#738]
- [ ] As a User I want to see the relevant date next to the calendar icon on the product box view, reference:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/1a508f14-aa00-4e8a-ae31-58aa4ad8198c)
** This data is valid only for: Publication, Training, Software,Data, Other, IG**
- [ ] As a User I don't want to see any icon if there is no date connected with the product (**valid for Services, Data Sources, , Bundles**)
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/92e160e5-f4ac-4dd4-9998-75f76a63c036)

- [ ] As a User I want to see year range filter for Data,Software,Publicaion and ORP
- [ ] **General remark** - When specific object/record (Publication, Training, Software,Data, Other, IG) has no data included - calendar icon must be hidden.

**Comment by agpul** [comment]
Estimation: 1 day

**Comment by eldenkat** [comment]
1. Looks rather ugly
2. Would be better to remove words "start year" and "end year"
![Zrzut ekranu 2023-08-07 140925](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/44f05cad-4c41-4def-925f-79818c09b687)

**Comment by eldenkat** [comment]
As it was mentioned in the ticket - date is spare for interoperability guidelines.

![Zrzut ekranu 2023-08-07 150313](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/ec2873d5-8740-46eb-a651-c3d49d70a89c)

**Comment by agpul** [comment]
publication_year - cut day nad month
