### ISSUE TITLE
Fix the PIDs in the research products view

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#765]
Currently, we use the DOI as a filter on the research products box view (this is a bad attitude)

Acceptance criteria:
- [x] As a User I would like to have the DOI as a link to an external page (each DOI should have the external link)
- [x] As a User I would like to see other identificatory if exists. (these identificators should look and behave as DOI)

List of identificators:
- HANDLE
- .DOI
- PMID
- PMD

Figma: https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

**Comment by wujuu** [comment]
Only addresses the DOI in the #808. Will add other identifiers once I have local data source sorted out.
