### ISSUE TITLE
Move the product type under the title and if necessary display it together with Document type

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#782]
Acceptance criteria:
- [x] As a User I would like to see document type under the title (not above) and if possible it should be displayed together with "Document type" field

Products with document type:
- [x] Publication
- [x] Data
- [x] Training
- [x] Other

Tip:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/1452ad37-ceaa-493e-a30d-ab303c0551c3)

Figma:
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

**Comment by wujuu** [comment]
@agpul what about Horizontal service tag? Should we create an issue for that or should I address it here as well?

**Comment by agpul** [comment]
address it here if possible
