### ISSUE TITLE
Move the access type under the title and change the text into logo

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#783]
Acceptance criteria:
- [x] As a User I would like to see the access type  as an icon under the title

Tip:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/950a9d1e-361a-42a9-90e3-300fcaece620)

Figma:
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

**Comment by wujuu** [comment]
There is no icon for restricted access types
