### ISSUE TITLE
Add a "Cite" functionality for Publications, Data, Software and Other

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#789]
- [ ] As a User I would like to use the "Cite" button (as a reference see: https://explore.openaire.eu/search/find/research-outcomes?resultbestaccessright=%22Open%2520Access%22 )
- [ ] As a User I would like to generate the citation using many styles (exactly the same as in Most wiedzy: APA, Harvard, Vancouver, Chicago, MLA)
- [ ] As a user I can copy my citation using "Copy Citation" button **(for citation only copy, not download!!)**
- [ ] As a User i would like to have the possibility to choose the proper Source (if Source>1) before creating the Export

Figma:
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=581%3A3760&mode=design&t=NTnOwHjNldAX04zI-1

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=279%3A4913&mode=design&t=pvF6dbXNvh8VLE37-1
