### ISSUE TITLE
Add "Export" functionality for Publications, Data, Software, ORP

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#790]
- [ ] As a User I would like to click the "Export" button that opens the additional window with two fields (Select an export style, Copy export)
- [ ] As a user I would like to copy and download all the info that we have in the "box" in different formats (see eksportuj as an example: https://mostwiedzy.pl/pl/publication/badania-mikrostrugowego-wymiennika-ciepla-czesc-2-badania-ekstremalne,132006-1)
- [ ] As a User i would like to have the possibility to choose the proper Source (if Source>1) before creating the Citation

Figma: https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=rViMb5bYCcQzoqWT-4

For the moment we limit the scope of the task to the documents with DOI, clicking "export" should open a modal with a drop-down "select source" which will display one entry per a DOI. We make a call to an external API to get properly formatted data.

Other cases (other identifiers and documents with no PID) will be covered in separated tickets.

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=279%3A4913&mode=design&t=pvF6dbXNvh8VLE37-1 modale
