### ISSUE TITLE
Fix the tooltip functionality for recommendation

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#811]
Acceptance criteria:
- [x] For unlogged user change the tooltip as follow:
Not Logged In? Discover Trending Picks: Recommended resources reflect what's popular among other users right now. Log in to access personalized suggestions curated just for you, influenced by your interests and actions on the EOSC Platform

- [x] For logged in user change the tooltip as follow: 
A recommender system suggests resources—like data sets, publications, software, trainings, and more. It looks at your past orders, views, and interactions. It also considers what others with similar interests have engaged with. The more you explore, the smarter the suggestions get. Your journey shapes your suggestions! 

Printscreen:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/8dfda4fd-f774-4cbc-9d56-af27e8b21de9)

**Comment by aleksandrahojszyk** [comment]
+ change Recommended for you to " Reccomended resources "
