### ISSUE TITLE
Organizacje i Projekty w SS

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#839]
- zrobić design dala boxa (based on OpenAire)
- skonsultowac z Wiktorem + MichałKO

nowa figma:

https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=508%3A7820&mode=design&t=N8gJdBaLNjgLLMAL-1

stara figma:
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=4690%3A1629&mode=design&t=GeVzxxPvfmPJS0mm-1

https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=4691%3A2264&mode=design&t=GeVzxxPvfmPJS0mm-1

**Comment by agpul** [comment]
Stan na 18/10/23 -> brak danych w danych od OpenAire

**Comment by Karolina9824** [comment]
figma:
https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=4027%3A32133&mode=design&t=xfqEukG5KB8ebQ3E-1
