### ISSUE TITLE
Interoperability guidelines content duplicate

### ISSUE THREAD

**Issue by eldenkat** [cyfronet-fid/eosc-search-service#840]
1. Go to interoperability guidelines
2. See the right side pannel (Basic details) and see duplicated content:

![Zrzut ekranu 2023-08-30 081937](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/b2157c1c-b789-4156-b398-b8eca3d0db6c)

3.See the PC guideline form:

- publication year - this field is completed only once
- created - this field is completed only once
- updated - this field is completed only once
- status - this field is completed only once
- domain - this field is completed only once
- resource type general - skipped
- resoutce type - can be completed more than once

![Zrzut ekranu 2023-08-30 082321](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/56539885-8251-4449-8649-1a668bf81c1f)

![Zrzut ekranu 2023-08-30 082553](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/c6b04561-8afb-4e3a-a0a0-c239bc76e173)

![Zrzut ekranu 2023-08-30 082646](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/851cc560-3563-423f-b798-4dd54b776b55)

![Zrzut ekranu 2023-08-30 083538](https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/c3af06e3-ad07-4edb-a8f2-cab73c3ebbd7)

**Expected behaviour**
1. Remove duplicates and fix the bug

**Comment by agpul** [comment]
done
