### ISSUE TITLE
Prepare separate SOLR collections for Organisation and Projects

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#858]
Acceptance criteria:
- [ ] As a User I want to see two separate dedicated collection that contains information about Projects and Organisation
- [ ] Schema for this collections should be established together with @aleksandrahojszyk

**Comment by Michal-Kolomanski** [comment]
On hold due to lack of data: https://docs.google.com/spreadsheets/d/1TCWYid_sDYhu5O23PD1VVY_wSQY_uWzrheHC1obhank/edit#gid=0

**Comment by agpul** [comment]
duplication
