### ISSUE TITLE
Design for Advanced Search User Giude

### ISSUE THREAD

**Issue by eldenkat** [cyfronet-fid/eosc-search-service#880]
Text:
https://docs.google.com/document/d/1FCi0Bd3_LGMq6-fth8C7ir-xqkAfD-RuLjB53JQ-z84/edit

**Comment by AlicjaSwierad** [comment]
Done

https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=94%3A3514&mode=design&t=mAUZhuVhJ6a6BW9d-1

**Comment by AlicjaSwierad** [comment]
https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=155%3A887&mode=design&t=8CppuQDckJtn3PYR-1

**Comment by AlicjaSwierad** [comment]
https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=322%3A6517&mode=design&t=Rj1GynBmcm4y9Pht-1
