### ISSUE TITLE
Ammendments and further development of Basic and Advanced Search

### ISSUE THREAD

**Issue by eldenkat** [cyfronet-fid/eosc-search-service#885]
- [ ] Add "_" and Ø  as a special charakters

- [ ] Add the possibility to search by Provider for the basic search (note, field name for specific collection: organization - in Services, data sources; providers - dla treningów, author - IG, provided by - dla bundle)

- [ ] "Polish letters" case -search by author soes not see letters typical for particular language and special signs (If you ebter Pulapa it wont display Pułapa, if you enter Sanchez it wont display Sánchez.
- [ ] Exact match still separates uppercase and lowercase letters in the same phrase (eg. when search neuroml it doesnt highlight neuroML
- [ ] With the "exact" operator, records are searched both with and without a special character in the typed query. But highlights are only in results with special char. - not done

- [ ] no highlight for trainings ad IG and prividers

**Comment by Marcelinna** [comment]
Wpisuje 
_Provider 23.10_ provider 23.10.2023 nie jest wysoko
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/d108e832-e9be-4cf2-a62e-ff448752c7a8)
_Provider 23.10.2023_
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/9f777c8d-9300-44cb-9743-a5f30e31a4cb)

**Comment by Marcelinna** [comment]
no highlighted  [= Band 5 der Kritischen Ausgabe].
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/59872096/17387acf-0943-4f3e-ba65-40e7de4d4191)
