### ISSUE TITLE
UI for Advanced Search and AS Guide

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#965]
As a scope of this issue:
- [ ] add proper styles to the AS Guide: https://beta.search.marketplace.eosc-portal.eu/asguide
- [ ] add proper styles to this view:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/8da43809-6d68-4da4-91c2-1885a853ec8d)
- [ ] this one should be also white:
![image](https://github.com/cyfronet-fid/eosc-search-service/assets/43000481/99728536-6a15-4ede-acd3-dddf483e6027)
- [ ] see comments in Figma to adjust the sizes of fonts and images: https://www.figma.com/file/thf78Tiwv9qNGuorwLG1ti/Search?type=design&node-id=691-1241&mode=design&t=XWXhk65fQaxf3FC1-0
- [] see figma for advanced search guide - the Instructions: https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=322%3A6517&mode=design&t=MyFWFI1wZXXFKMrl-1

**Comment by eldenkat** [comment]
Not sure, seems like we have 3 font sizes here? Maybe 2 would be enough?
<img width="940" alt="Screenshot 2023-10-23 at 09 46 40" src="https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/0b8b59c5-51a5-4434-9188-1b9b38cec14b">

**Comment by eldenkat** [comment]
Align the size of the icons
<img width="1015" alt="Screenshot 2023-10-23 at 11 03 16" src="https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/272c0ee5-4ddc-4d9e-9ef5-3263775be8ae">

**Comment by eldenkat** [comment]
that doesn't look good:
<img width="1086" alt="Screenshot 2023-10-23 at 11 55 02" src="https://github.com/cyfronet-fid/eosc-search-service/assets/113451713/d2a340bc-9dad-4981-96fd-22d2de04ad35">
